### ISSUE TITLE
Code uses WebClient but blocks

### ISSUE THREAD

**Issue by marschall** [admin-ch/CovidCertificate-Management-Service#126]
The code uses the reactive `WebClient` but ends up calling `#block()` which, as the name suggests, blocks and therefore defeats the whole purpose of using `WebClient` in the first place. Examples:

- https://github.com/admin-ch/CovidCertificate-Management-Service/blob/638a2607b2a0f6441437ca0500fa6386c5bf7a67/src/main/java/ch/admin/bag/covidcertificate/client/printing/internal/DefaultPrintQueueClient.java#L43
- https://github.com/admin-ch/CovidCertificate-Management-Service/blob/b03d2efcd45f6e40e40ffc98549f1c9f000b61e9/src/main/java/ch/admin/bag/covidcertificate/client/valuesets/internal/DefaultValueSetsClient.java#L41
- https://github.com/admin-ch/CovidCertificate-Management-Service/blob/74c2ca7bb4c45616cba91ecf592814115f246fa9/src/main/java/ch/admin/bag/covidcertificate/client/inapp_delivery/internal/DefaultInAppDeliveryClient.java#L53

The code should instead do one of the following:
- Avoid calling `#block()` and instead call `#subscribe()`
- Switch from the reactive `WebClient` to the blocking `RestTemplate`

Considering all the rest of the code is blocking (`JpaRepository`, …) `WebClient` seems like the better match.

**Comment by marschall** [comment]
@Armin-Isenring-Bit what is the reason for closing?

**Comment by Armin-Isenring-Bit** [comment]
@marschall we have been investigating both suggested changes due to unwanted behaviour in the service grid (which this service is a major part of). Both had disadvantages which of this time the team does not want to buy in. We are still doing research in this matter.
Your comment is a good point, closing it has nothing to do with its quality or the substance of your concern.

**Comment by marschall** [comment]
@Armin-Isenring-Bit fair enough
